# GitHub Pages Configuration
theme: jekyll-theme-minimal
title: PEPEBALL Dashboard
description: The Ultimate Powerball Lottery Token
baseurl: ""
url: "https://preseteth.github.io/pepeball"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
