// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.589Z
// Collection: drawings/$drawingId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * Basic drawing records for tracking lottery rounds
 */

export interface DrawingsRequest {
  status: string;
  endTime?: number | TimeOperation | IncrementOperation | TokenAmount;
  jackpot?: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface DrawingsResponse {
  status: string;
  endTime?: number;
  jackpot?: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Drawings operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDrawings(drawingId: string, data: DrawingsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `drawings/${drawingId}`, document: doc };
}

/**
 * Anyone can create a drawing for stress testing. Set status to 'active' for new drawings. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setDrawings(drawingId: string, data: DrawingsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`drawings/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Drawings: ${formatError(error)}`);
    return false;
  }
}

export type DrawingsRequestUpdate = Partial<DrawingsRequest>;

/**
 * Build a Drawings update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateDrawings(drawingId: string, data: DrawingsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `drawings/${drawingId}`, document: doc };
}

/**
 * Anyone can update drawing status (active to completed) and add results for stress testing. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateDrawings(drawingId: string, data: DrawingsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`drawings/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Drawings: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
   (Get Single Item)
 */
export async function getDrawings(drawingId: string): Promise<DrawingsResponse | null> {
  try {
    const result = await get(`drawings/${drawingId}`);
    return result as DrawingsResponse | null;
  } catch (error) {
    console.error(`Error getting Drawings: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Drawings document. (
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
  )
 */
export function subscribeDrawings(callback: (data: DrawingsResponse | null) => void, drawingId: string): Promise<() => Promise<void>> {
  return subscribe(`drawings/${drawingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as DrawingsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Drawings at path '${`drawings/${drawingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Drawings items from collection drawings
 
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
  
 */
export async function getManyDrawings(filter: string = ""): Promise<DrawingsResponse[]> {
  try {
    const results = await get("drawings", { prompt: filter });
    return Array.isArray(results) ? results as DrawingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Drawings collection at path 'drawings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Drawings collection at drawings
 
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
  
 */
export function subscribeManyDrawings(callback: (data: DrawingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("drawings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as DrawingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Drawings collection at path '${"drawings"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Drawings items from collection drawings
 
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
  
 */
export async function getAllDrawings(filter: string = ""): Promise<DrawingsResponse[]> {
  try {
    const results = await get("drawings", { prompt: filter });
    return Array.isArray(results) ? results as DrawingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Drawings collection at path 'drawings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Drawings collection at drawings
 
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
  
 */
export function subscribeAllDrawings(callback: (data: DrawingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("drawings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as DrawingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Drawings collection at path '${"drawings"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Anyone can delete drawings for stress testing.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteDrawings(drawingId: string): Promise<boolean> {
  try {
    const succeeded = await set(`drawings/${drawingId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Drawings: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Drawings for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteDrawings(drawingId: string): DocumentOperation {
  return { path: `drawings/${drawingId}`, document: null };
}

