// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.589Z
// Collection: vrfDrawings/$drawingId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * VRF lottery drawings - admin triggers drawing, oracle reveals result
 */

export interface VrfDrawingsRequest {
  drawNum: number | TimeOperation | IncrementOperation | TokenAmount;
  jackpot: number | TimeOperation | IncrementOperation | TokenAmount;
  entries: number | TimeOperation | IncrementOperation | TokenAmount;
  result?: number | TimeOperation | IncrementOperation | TokenAmount;
  winner?: AddressType;
  payout?: number | TimeOperation | IncrementOperation | TokenAmount;
  settled?: boolean;
  payoutTxHash?: string;
  evenOddResult?: string;
  scheduledRevealAt?: number | TimeOperation | IncrementOperation | TokenAmount;
  actualRevealAt?: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface VrfDrawingsResponse {
  drawNum: number;
  jackpot: number;
  entries: number;
  result?: number;
  winner?: string;
  payout?: number;
  settled?: boolean;
  payoutTxHash?: string;
  evenOddResult?: string;
  scheduledRevealAt?: number;
  actualRevealAt?: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a VrfDrawings operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildVrfDrawings(drawingId: string, data?: VrfDrawingsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `vrfDrawings/${drawingId}`, document: doc };
}

/**
 * Admin triggers a lottery drawing. Requests VRF randomness. Drawing ID should be unique (e.g., draw_1, draw_2). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setVrfDrawings(drawingId: string, data?: VrfDrawingsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`vrfDrawings/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting VrfDrawings: ${formatError(error)}`);
    return false;
  }
}

export type VrfDrawingsRequestUpdate = Partial<VrfDrawingsRequest>;

/**
 * Build a VrfDrawings update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateVrfDrawings(drawingId: string, data: VrfDrawingsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `vrfDrawings/${drawingId}`, document: doc };
}

/**
 * Admin or oracle callback updates drawing with result, winner, and payout after VRF reveals. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateVrfDrawings(drawingId: string, data: VrfDrawingsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`vrfDrawings/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating VrfDrawings: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
   (Get Single Item)
 */
export async function getVrfDrawings(drawingId: string): Promise<VrfDrawingsResponse | null> {
  try {
    const result = await get(`vrfDrawings/${drawingId}`);
    return result as VrfDrawingsResponse | null;
  } catch (error) {
    console.error(`Error getting VrfDrawings: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single VrfDrawings document. (
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
  )
 */
export function subscribeVrfDrawings(callback: (data: VrfDrawingsResponse | null) => void, drawingId: string): Promise<() => Promise<void>> {
  return subscribe(`vrfDrawings/${drawingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as VrfDrawingsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to VrfDrawings at path '${`vrfDrawings/${drawingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many VrfDrawings items from collection vrfDrawings
 
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
  
 */
export async function getManyVrfDrawings(filter: string = ""): Promise<VrfDrawingsResponse[]> {
  try {
    const results = await get("vrfDrawings", { prompt: filter });
    return Array.isArray(results) ? results as VrfDrawingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfDrawings collection at path 'vrfDrawings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfDrawings collection at vrfDrawings
 
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
  
 */
export function subscribeManyVrfDrawings(callback: (data: VrfDrawingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfDrawings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfDrawingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfDrawings collection at path '${"vrfDrawings"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all VrfDrawings items from collection vrfDrawings
 
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
  
 */
export async function getAllVrfDrawings(filter: string = ""): Promise<VrfDrawingsResponse[]> {
  try {
    const results = await get("vrfDrawings", { prompt: filter });
    return Array.isArray(results) ? results as VrfDrawingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfDrawings collection at path 'vrfDrawings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfDrawings collection at vrfDrawings
 
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
  
 */
export function subscribeAllVrfDrawings(callback: (data: VrfDrawingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfDrawings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfDrawingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfDrawings collection at path '${"vrfDrawings"}': ${formatError(error)}`);
    }
  });
}

/**
 * Runs the "getVRFAddress" query on VrfDrawings.
 * Query Logic: @OraclePlugin.getVRFAddress($drawingId)
 */
export async function runGetVRFAddressQueryForVrfDrawings(drawingId: string, ): Promise<string> {
  try {
    const result = await runQuery(`vrfDrawings/${drawingId}`, "getVRFAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getVRFAddress" on VrfDrawings: ${formatError(error)}`);
    throw error;
  }
}

