// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.589Z
// Collection: vrfEntries/$entryId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * VRF lottery entries - token-gated, requires minimum PEPEBALL holding
 */

export interface VrfEntriesRequest {
  drawId: string;
  wallet: AddressType;
  idx: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface VrfEntriesResponse {
  drawId: string;
  wallet: string;
  idx: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a VrfEntries operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildVrfEntries(entryId: string, data?: VrfEntriesRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `vrfEntries/${entryId}`, document: doc };
}

/**
 * Anyone holding at least MIN_HOLDING_TOKENS (1000 tokens with 9 decimals) of PEPEBALL can register as entry. Entry ID should be drawId_wallet format. idx is the entry index (0-based) for winner selection. Validates user holds minimum PEPEBALL balance before allowing entry. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setVrfEntries(entryId: string, data?: VrfEntriesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`vrfEntries/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting VrfEntries: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
   (Get Single Item)
 */
export async function getVrfEntries(entryId: string): Promise<VrfEntriesResponse | null> {
  try {
    const result = await get(`vrfEntries/${entryId}`);
    return result as VrfEntriesResponse | null;
  } catch (error) {
    console.error(`Error getting VrfEntries: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single VrfEntries document. (
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
  )
 */
export function subscribeVrfEntries(callback: (data: VrfEntriesResponse | null) => void, entryId: string): Promise<() => Promise<void>> {
  return subscribe(`vrfEntries/${entryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as VrfEntriesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to VrfEntries at path '${`vrfEntries/${entryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many VrfEntries items from collection vrfEntries
 
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
  
 */
export async function getManyVrfEntries(filter: string = ""): Promise<VrfEntriesResponse[]> {
  try {
    const results = await get("vrfEntries", { prompt: filter });
    return Array.isArray(results) ? results as VrfEntriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfEntries collection at path 'vrfEntries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfEntries collection at vrfEntries
 
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
  
 */
export function subscribeManyVrfEntries(callback: (data: VrfEntriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfEntries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfEntriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfEntries collection at path '${"vrfEntries"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all VrfEntries items from collection vrfEntries
 
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
  
 */
export async function getAllVrfEntries(filter: string = ""): Promise<VrfEntriesResponse[]> {
  try {
    const results = await get("vrfEntries", { prompt: filter });
    return Array.isArray(results) ? results as VrfEntriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfEntries collection at path 'vrfEntries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfEntries collection at vrfEntries
 
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
  
 */
export function subscribeAllVrfEntries(callback: (data: VrfEntriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfEntries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfEntriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfEntries collection at path '${"vrfEntries"}': ${formatError(error)}`);
    }
  });
}

