// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.589Z
// Collection: vrfReveals/$drawingId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * VRF callback - oracle creates reveal record after randomness is fulfilled
 */

export interface VrfRevealsRequest {

}

export interface VrfRevealsResponse {

  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a VrfReveals operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildVrfReveals(drawingId: string, data?: VrfRevealsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `vrfReveals/${drawingId}`, document: doc };
}

/**
 * Oracle callback. Reads random number in range [0, entries), updates drawing with result. Winner selection done offchain based on result index. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setVrfReveals(drawingId: string, data?: VrfRevealsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`vrfReveals/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting VrfReveals: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
   (Get Single Item)
 */
export async function getVrfReveals(drawingId: string): Promise<VrfRevealsResponse | null> {
  try {
    const result = await get(`vrfReveals/${drawingId}`);
    return result as VrfRevealsResponse | null;
  } catch (error) {
    console.error(`Error getting VrfReveals: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single VrfReveals document. (
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
  )
 */
export function subscribeVrfReveals(callback: (data: VrfRevealsResponse | null) => void, drawingId: string): Promise<() => Promise<void>> {
  return subscribe(`vrfReveals/${drawingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as VrfRevealsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to VrfReveals at path '${`vrfReveals/${drawingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many VrfReveals items from collection vrfReveals
 
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
  
 */
export async function getManyVrfReveals(filter: string = ""): Promise<VrfRevealsResponse[]> {
  try {
    const results = await get("vrfReveals", { prompt: filter });
    return Array.isArray(results) ? results as VrfRevealsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfReveals collection at path 'vrfReveals': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfReveals collection at vrfReveals
 
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
  
 */
export function subscribeManyVrfReveals(callback: (data: VrfRevealsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfReveals", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfRevealsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfReveals collection at path '${"vrfReveals"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all VrfReveals items from collection vrfReveals
 
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
  
 */
export async function getAllVrfReveals(filter: string = ""): Promise<VrfRevealsResponse[]> {
  try {
    const results = await get("vrfReveals", { prompt: filter });
    return Array.isArray(results) ? results as VrfRevealsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfReveals collection at path 'vrfReveals': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfReveals collection at vrfReveals
 
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
  
 */
export function subscribeAllVrfReveals(callback: (data: VrfRevealsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfReveals", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfRevealsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfReveals collection at path '${"vrfReveals"}': ${formatError(error)}`);
    }
  });
}

