// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.572Z
// Collection: entries/$entryId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * Basic lottery entries for offchain tracking
 */

export interface EntriesRequest {
  wallet: AddressType;
  drawingId: string;
  tokenBalance: number | TimeOperation | IncrementOperation | TokenAmount;
  enteredAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface EntriesResponse {
  wallet: string;
  drawingId: string;
  tokenBalance: number;
  enteredAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Entries operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildEntries(entryId: string, data: EntriesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `entries/${entryId}`, document: doc };
}

/**
 * Anyone can create entries (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setEntries(entryId: string, data: EntriesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`entries/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Entries: ${formatError(error)}`);
    return false;
  }
}

export type EntriesRequestUpdate = Partial<EntriesRequest>;

/**
 * Build a Entries update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateEntries(entryId: string, data: EntriesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `entries/${entryId}`, document: doc };
}

/**
 * Anyone can update entries (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateEntries(entryId: string, data: EntriesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`entries/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Entries: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read entries
   (Get Single Item)
 */
export async function getEntries(entryId: string): Promise<EntriesResponse | null> {
  try {
    const result = await get(`entries/${entryId}`);
    return result as EntriesResponse | null;
  } catch (error) {
    console.error(`Error getting Entries: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Entries document. (
  Read Operation Details: Anyone can read entries
  )
 */
export function subscribeEntries(callback: (data: EntriesResponse | null) => void, entryId: string): Promise<() => Promise<void>> {
  return subscribe(`entries/${entryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as EntriesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Entries at path '${`entries/${entryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Entries items from collection entries
 
  Read Operation Details: Anyone can read entries
  
 */
export async function getManyEntries(filter: string = ""): Promise<EntriesResponse[]> {
  try {
    const results = await get("entries", { prompt: filter });
    return Array.isArray(results) ? results as EntriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Entries collection at path 'entries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Entries collection at entries
 
  Read Operation Details: Anyone can read entries
  
 */
export function subscribeManyEntries(callback: (data: EntriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("entries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as EntriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Entries collection at path '${"entries"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Entries items from collection entries
 
  Read Operation Details: Anyone can read entries
  
 */
export async function getAllEntries(filter: string = ""): Promise<EntriesResponse[]> {
  try {
    const results = await get("entries", { prompt: filter });
    return Array.isArray(results) ? results as EntriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Entries collection at path 'entries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Entries collection at entries
 
  Read Operation Details: Anyone can read entries
  
 */
export function subscribeAllEntries(callback: (data: EntriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("entries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as EntriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Entries collection at path '${"entries"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Anyone can delete entries
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteEntries(entryId: string): Promise<boolean> {
  try {
    const succeeded = await set(`entries/${entryId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Entries: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Entries for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteEntries(entryId: string): DocumentOperation {
  return { path: `entries/${entryId}`, document: null };
}

