// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.572Z
// Collection: feeHarvests/$harvestId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * Records of fee harvests from the token transfer tax
 */

export interface FeeHarvestsRequest {
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
  harvestedAt: number | TimeOperation | IncrementOperation | TokenAmount;
  harvestedBy: AddressType;
  tokenMint: string;
  txSignature?: string;
}

export interface FeeHarvestsResponse {
  amount: number;
  harvestedAt: number;
  harvestedBy: string;
  tokenMint: string;
  txSignature?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a FeeHarvests operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildFeeHarvests(harvestId: string, data: FeeHarvestsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `feeHarvests/${harvestId}`, document: doc };
}

/**
 * Admin only. Records a fee harvest event with amount in smallest units (lamports), timestamp, harvester address, token mint, and optional transaction signature. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setFeeHarvests(harvestId: string, data: FeeHarvestsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`feeHarvests/${harvestId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting FeeHarvests: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
   (Get Single Item)
 */
export async function getFeeHarvests(harvestId: string): Promise<FeeHarvestsResponse | null> {
  try {
    const result = await get(`feeHarvests/${harvestId}`);
    return result as FeeHarvestsResponse | null;
  } catch (error) {
    console.error(`Error getting FeeHarvests: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single FeeHarvests document. (
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
  )
 */
export function subscribeFeeHarvests(callback: (data: FeeHarvestsResponse | null) => void, harvestId: string): Promise<() => Promise<void>> {
  return subscribe(`feeHarvests/${harvestId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as FeeHarvestsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to FeeHarvests at path '${`feeHarvests/${harvestId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many FeeHarvests items from collection feeHarvests
 
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
  
 */
export async function getManyFeeHarvests(filter: string = ""): Promise<FeeHarvestsResponse[]> {
  try {
    const results = await get("feeHarvests", { prompt: filter });
    return Array.isArray(results) ? results as FeeHarvestsResponse[] : [];
  } catch (error) {
    console.error(`Error getting FeeHarvests collection at path 'feeHarvests': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FeeHarvests collection at feeHarvests
 
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
  
 */
export function subscribeManyFeeHarvests(callback: (data: FeeHarvestsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("feeHarvests", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FeeHarvestsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FeeHarvests collection at path '${"feeHarvests"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all FeeHarvests items from collection feeHarvests
 
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
  
 */
export async function getAllFeeHarvests(filter: string = ""): Promise<FeeHarvestsResponse[]> {
  try {
    const results = await get("feeHarvests", { prompt: filter });
    return Array.isArray(results) ? results as FeeHarvestsResponse[] : [];
  } catch (error) {
    console.error(`Error getting FeeHarvests collection at path 'feeHarvests': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FeeHarvests collection at feeHarvests
 
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
  
 */
export function subscribeAllFeeHarvests(callback: (data: FeeHarvestsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("feeHarvests", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FeeHarvestsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FeeHarvests collection at path '${"feeHarvests"}': ${formatError(error)}`);
    }
  });
}

