// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.572Z
// Collection: houseFunding/$fundingId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * Admin deposits SOL into house escrow for payouts
 */

export interface HouseFundingRequest {
  amt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface HouseFundingResponse {
  amt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a HouseFunding operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildHouseFunding(fundingId: string, data?: HouseFundingRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `houseFunding/${fundingId}`, document: doc };
}

/**
 * Admin deposits SOL to fund house for lottery payouts. Transfers SOL from admin to house PDA. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setHouseFunding(fundingId: string, data?: HouseFundingRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`houseFunding/${fundingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting HouseFunding: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view funding history for transparency.
   (Get Single Item)
 */
export async function getHouseFunding(fundingId: string): Promise<HouseFundingResponse | null> {
  try {
    const result = await get(`houseFunding/${fundingId}`);
    return result as HouseFundingResponse | null;
  } catch (error) {
    console.error(`Error getting HouseFunding: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single HouseFunding document. (
  Read Operation Details: Anyone can view funding history for transparency.
  )
 */
export function subscribeHouseFunding(callback: (data: HouseFundingResponse | null) => void, fundingId: string): Promise<() => Promise<void>> {
  return subscribe(`houseFunding/${fundingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as HouseFundingResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to HouseFunding at path '${`houseFunding/${fundingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many HouseFunding items from collection houseFunding
 
  Read Operation Details: Anyone can view funding history for transparency.
  
 */
export async function getManyHouseFunding(filter: string = ""): Promise<HouseFundingResponse[]> {
  try {
    const results = await get("houseFunding", { prompt: filter });
    return Array.isArray(results) ? results as HouseFundingResponse[] : [];
  } catch (error) {
    console.error(`Error getting HouseFunding collection at path 'houseFunding': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in HouseFunding collection at houseFunding
 
  Read Operation Details: Anyone can view funding history for transparency.
  
 */
export function subscribeManyHouseFunding(callback: (data: HouseFundingResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("houseFunding", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as HouseFundingResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to HouseFunding collection at path '${"houseFunding"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all HouseFunding items from collection houseFunding
 
  Read Operation Details: Anyone can view funding history for transparency.
  
 */
export async function getAllHouseFunding(filter: string = ""): Promise<HouseFundingResponse[]> {
  try {
    const results = await get("houseFunding", { prompt: filter });
    return Array.isArray(results) ? results as HouseFundingResponse[] : [];
  } catch (error) {
    console.error(`Error getting HouseFunding collection at path 'houseFunding': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in HouseFunding collection at houseFunding
 
  Read Operation Details: Anyone can view funding history for transparency.
  
 */
export function subscribeAllHouseFunding(callback: (data: HouseFundingResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("houseFunding", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as HouseFundingResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to HouseFunding collection at path '${"houseFunding"}': ${formatError(error)}`);
    }
  });
}

