// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.572Z
// Collection: jackpot/$jackpotId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * Tracks lottery jackpot state including balance, next drawing time, and drawing count
 */

export interface JackpotRequest {
  balance: number | TimeOperation | IncrementOperation | TokenAmount;
  nextDrawingAt: number | TimeOperation | IncrementOperation | TokenAmount;
  drawingNumber: number | TimeOperation | IncrementOperation | TokenAmount;
  isOver200Sol: boolean;
  lastUpdatedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface JackpotResponse {
  balance: number;
  nextDrawingAt: number;
  drawingNumber: number;
  isOver200Sol: boolean;
  lastUpdatedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Jackpot operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildJackpot(jackpotId: string, data: JackpotRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `jackpot/${jackpotId}`, document: doc };
}

/**
 * Anyone can create the jackpot document for stress testing. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setJackpot(jackpotId: string, data: JackpotRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`jackpot/${jackpotId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Jackpot: ${formatError(error)}`);
    return false;
  }
}

export type JackpotRequestUpdate = Partial<JackpotRequest>;

/**
 * Build a Jackpot update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateJackpot(jackpotId: string, data: JackpotRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `jackpot/${jackpotId}`, document: doc };
}

/**
 * Anyone can update balance, nextDrawingAt, drawingNumber, and isOver200Sol flag for stress testing. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateJackpot(jackpotId: string, data: JackpotRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`jackpot/${jackpotId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Jackpot: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
   (Get Single Item)
 */
export async function getJackpot(jackpotId: string): Promise<JackpotResponse | null> {
  try {
    const result = await get(`jackpot/${jackpotId}`);
    return result as JackpotResponse | null;
  } catch (error) {
    console.error(`Error getting Jackpot: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Jackpot document. (
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
  )
 */
export function subscribeJackpot(callback: (data: JackpotResponse | null) => void, jackpotId: string): Promise<() => Promise<void>> {
  return subscribe(`jackpot/${jackpotId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as JackpotResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Jackpot at path '${`jackpot/${jackpotId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Jackpot items from collection jackpot
 
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
  
 */
export async function getManyJackpot(filter: string = ""): Promise<JackpotResponse[]> {
  try {
    const results = await get("jackpot", { prompt: filter });
    return Array.isArray(results) ? results as JackpotResponse[] : [];
  } catch (error) {
    console.error(`Error getting Jackpot collection at path 'jackpot': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Jackpot collection at jackpot
 
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
  
 */
export function subscribeManyJackpot(callback: (data: JackpotResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("jackpot", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as JackpotResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Jackpot collection at path '${"jackpot"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Jackpot items from collection jackpot
 
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
  
 */
export async function getAllJackpot(filter: string = ""): Promise<JackpotResponse[]> {
  try {
    const results = await get("jackpot", { prompt: filter });
    return Array.isArray(results) ? results as JackpotResponse[] : [];
  } catch (error) {
    console.error(`Error getting Jackpot collection at path 'jackpot': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Jackpot collection at jackpot
 
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
  
 */
export function subscribeAllJackpot(callback: (data: JackpotResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("jackpot", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as JackpotResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Jackpot collection at path '${"jackpot"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Anyone can delete the jackpot document for stress testing.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteJackpot(jackpotId: string): Promise<boolean> {
  try {
    const succeeded = await set(`jackpot/${jackpotId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Jackpot: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Jackpot for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteJackpot(jackpotId: string): DocumentOperation {
  return { path: `jackpot/${jackpotId}`, document: null };
}

