// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.572Z
// Collection: jackpotDeposits/$depositId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * Records of admin SOL deposits to fund the jackpot
 */

export interface JackpotDepositsRequest {
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
  depositedBy: AddressType;
  depositedAt: number | TimeOperation | IncrementOperation | TokenAmount;
  note?: string;
}

export interface JackpotDepositsResponse {
  amount: number;
  depositedBy: string;
  depositedAt: number;
  note?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a JackpotDeposits operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildJackpotDeposits(depositId: string, data: JackpotDepositsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `jackpotDeposits/${depositId}`, document: doc };
}

/**
 * Admin deposits SOL to fund the jackpot. For testing phase, this is manual. Later will be automated via buy/sell tax. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setJackpotDeposits(depositId: string, data: JackpotDepositsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`jackpotDeposits/${depositId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting JackpotDeposits: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view deposit history for transparency.
   (Get Single Item)
 */
export async function getJackpotDeposits(depositId: string): Promise<JackpotDepositsResponse | null> {
  try {
    const result = await get(`jackpotDeposits/${depositId}`);
    return result as JackpotDepositsResponse | null;
  } catch (error) {
    console.error(`Error getting JackpotDeposits: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single JackpotDeposits document. (
  Read Operation Details: Anyone can view deposit history for transparency.
  )
 */
export function subscribeJackpotDeposits(callback: (data: JackpotDepositsResponse | null) => void, depositId: string): Promise<() => Promise<void>> {
  return subscribe(`jackpotDeposits/${depositId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as JackpotDepositsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to JackpotDeposits at path '${`jackpotDeposits/${depositId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many JackpotDeposits items from collection jackpotDeposits
 
  Read Operation Details: Anyone can view deposit history for transparency.
  
 */
export async function getManyJackpotDeposits(filter: string = ""): Promise<JackpotDepositsResponse[]> {
  try {
    const results = await get("jackpotDeposits", { prompt: filter });
    return Array.isArray(results) ? results as JackpotDepositsResponse[] : [];
  } catch (error) {
    console.error(`Error getting JackpotDeposits collection at path 'jackpotDeposits': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in JackpotDeposits collection at jackpotDeposits
 
  Read Operation Details: Anyone can view deposit history for transparency.
  
 */
export function subscribeManyJackpotDeposits(callback: (data: JackpotDepositsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("jackpotDeposits", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as JackpotDepositsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to JackpotDeposits collection at path '${"jackpotDeposits"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all JackpotDeposits items from collection jackpotDeposits
 
  Read Operation Details: Anyone can view deposit history for transparency.
  
 */
export async function getAllJackpotDeposits(filter: string = ""): Promise<JackpotDepositsResponse[]> {
  try {
    const results = await get("jackpotDeposits", { prompt: filter });
    return Array.isArray(results) ? results as JackpotDepositsResponse[] : [];
  } catch (error) {
    console.error(`Error getting JackpotDeposits collection at path 'jackpotDeposits': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in JackpotDeposits collection at jackpotDeposits
 
  Read Operation Details: Anyone can view deposit history for transparency.
  
 */
export function subscribeAllJackpotDeposits(callback: (data: JackpotDepositsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("jackpotDeposits", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as JackpotDepositsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to JackpotDeposits collection at path '${"jackpotDeposits"}': ${formatError(error)}`);
    }
  });
}

