// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.572Z
// Collection: lotteryHouse/$houseId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * House escrow PDA - holds SOL for lottery payouts
 */

export interface LotteryHouseRequest {
  active: boolean;
}

export interface LotteryHouseResponse {
  active: boolean;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a LotteryHouse operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildLotteryHouse(houseId: string, data?: LotteryHouseRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `lotteryHouse/${houseId}`, document: doc };
}

/**
 * Admin creates house escrow once. Creates PDA that holds SOL for lottery payouts. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setLotteryHouse(houseId: string, data?: LotteryHouseRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`lotteryHouse/${houseId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting LotteryHouse: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can check house balance and status for transparency.
   (Get Single Item)
 */
export async function getLotteryHouse(houseId: string): Promise<LotteryHouseResponse | null> {
  try {
    const result = await get(`lotteryHouse/${houseId}`);
    return result as LotteryHouseResponse | null;
  } catch (error) {
    console.error(`Error getting LotteryHouse: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single LotteryHouse document. (
  Read Operation Details: Anyone can check house balance and status for transparency.
  )
 */
export function subscribeLotteryHouse(callback: (data: LotteryHouseResponse | null) => void, houseId: string): Promise<() => Promise<void>> {
  return subscribe(`lotteryHouse/${houseId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as LotteryHouseResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to LotteryHouse at path '${`lotteryHouse/${houseId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many LotteryHouse items from collection lotteryHouse
 
  Read Operation Details: Anyone can check house balance and status for transparency.
  
 */
export async function getManyLotteryHouse(filter: string = ""): Promise<LotteryHouseResponse[]> {
  try {
    const results = await get("lotteryHouse", { prompt: filter });
    return Array.isArray(results) ? results as LotteryHouseResponse[] : [];
  } catch (error) {
    console.error(`Error getting LotteryHouse collection at path 'lotteryHouse': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in LotteryHouse collection at lotteryHouse
 
  Read Operation Details: Anyone can check house balance and status for transparency.
  
 */
export function subscribeManyLotteryHouse(callback: (data: LotteryHouseResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("lotteryHouse", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as LotteryHouseResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to LotteryHouse collection at path '${"lotteryHouse"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all LotteryHouse items from collection lotteryHouse
 
  Read Operation Details: Anyone can check house balance and status for transparency.
  
 */
export async function getAllLotteryHouse(filter: string = ""): Promise<LotteryHouseResponse[]> {
  try {
    const results = await get("lotteryHouse", { prompt: filter });
    return Array.isArray(results) ? results as LotteryHouseResponse[] : [];
  } catch (error) {
    console.error(`Error getting LotteryHouse collection at path 'lotteryHouse': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in LotteryHouse collection at lotteryHouse
 
  Read Operation Details: Anyone can check house balance and status for transparency.
  
 */
export function subscribeAllLotteryHouse(callback: (data: LotteryHouseResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("lotteryHouse", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as LotteryHouseResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to LotteryHouse collection at path '${"lotteryHouse"}': ${formatError(error)}`);
    }
  });
}

/**
 * Runs the "getHouseBalance" query on LotteryHouse.
 * Query Logic: @TokenPlugin.getBalance(@constants.LOTTERY_HOUSE_ID, @constants.SOL)
 */
export async function runGetHouseBalanceQueryForLotteryHouse(houseId: string, ): Promise<number> {
  try {
    const result = await runQuery(`lotteryHouse/${houseId}`, "getHouseBalance", {});
    return result as number;
  } catch (error) {
    console.error(`Error running query "getHouseBalance" on LotteryHouse: ${formatError(error)}`);
    throw error;
  }
}

