// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.572Z
// Collection: transfers/$transferId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * Token transfers with onchain execution
 */

export interface TransfersRequest {
  from: AddressType;
  to: AddressType;
  amt: number | TimeOperation | IncrementOperation | TokenAmount;
  mint: AddressType;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface TransfersResponse {
  from: string;
  to: string;
  amt: number;
  mint: string;
  ts: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a Transfers operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildTransfers(transferId: string, data?: TransfersRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `transfers/${transferId}`, document: doc };
}

/**
 * Authenticated users can create transfers FROM their own wallet only (from must equal user address). Hook executes @TokenPlugin.transfer onchain to move tokens. Amount is in raw units (9 decimals for PBALL). isPassthrough means data stored offchain only to reduce costs. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setTransfers(transferId: string, data?: TransfersRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`transfers/${transferId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Transfers: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
   (Get Single Item)
 */
export async function getTransfers(transferId: string): Promise<TransfersResponse | null> {
  try {
    const result = await get(`transfers/${transferId}`);
    return result as TransfersResponse | null;
  } catch (error) {
    console.error(`Error getting Transfers: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Transfers document. (
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
  )
 */
export function subscribeTransfers(callback: (data: TransfersResponse | null) => void, transferId: string): Promise<() => Promise<void>> {
  return subscribe(`transfers/${transferId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as TransfersResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Transfers at path '${`transfers/${transferId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Transfers items from collection transfers
 
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
  
 */
export async function getManyTransfers(filter: string = ""): Promise<TransfersResponse[]> {
  try {
    const results = await get("transfers", { prompt: filter });
    return Array.isArray(results) ? results as TransfersResponse[] : [];
  } catch (error) {
    console.error(`Error getting Transfers collection at path 'transfers': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Transfers collection at transfers
 
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
  
 */
export function subscribeManyTransfers(callback: (data: TransfersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("transfers", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TransfersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Transfers collection at path '${"transfers"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Transfers items from collection transfers
 
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
  
 */
export async function getAllTransfers(filter: string = ""): Promise<TransfersResponse[]> {
  try {
    const results = await get("transfers", { prompt: filter });
    return Array.isArray(results) ? results as TransfersResponse[] : [];
  } catch (error) {
    console.error(`Error getting Transfers collection at path 'transfers': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Transfers collection at transfers
 
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
  
 */
export function subscribeAllTransfers(callback: (data: TransfersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("transfers", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TransfersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Transfers collection at path '${"transfers"}': ${formatError(error)}`);
    }
  });
}

