// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.572Z
// Collection: vrfSettlements/$drawingId
// Edits may be overwritten by subsequent runs!

import {
  get, set, subscribe, getFiles, setFile, runQuery, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';

/**
 * Settlement records - admin settles lottery after VRF reveal
 */

export interface VrfSettlementsRequest {
  entryId: string;
  winner: AddressType;
  payout: number | TimeOperation | IncrementOperation | TokenAmount;
  fees: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface VrfSettlementsResponse {
  entryId: string;
  winner: string;
  payout: number;
  fees: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a VrfSettlements operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildVrfSettlements(drawingId: string, data?: VrfSettlementsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `vrfSettlements/${drawingId}`, document: doc };
}

/**
 * Admin only. Creates settlement by passing entryId (the winning entry ID in format drawId_wallet), winner wallet address, payout amount (in lamports after fees calculated), and fees amount. Hook validates: (1) drawing exists with result, (2) not already settled, (3) entry exists with matching idx to result, (4) entry wallet matches winner. Then transfers payout to winner, fees to admin, and marks drawing as settled. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setVrfSettlements(drawingId: string, data?: VrfSettlementsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`vrfSettlements/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting VrfSettlements: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view settlement records for transparency.
   (Get Single Item)
 */
export async function getVrfSettlements(drawingId: string): Promise<VrfSettlementsResponse | null> {
  try {
    const result = await get(`vrfSettlements/${drawingId}`);
    return result as VrfSettlementsResponse | null;
  } catch (error) {
    console.error(`Error getting VrfSettlements: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single VrfSettlements document. (
  Read Operation Details: Anyone can view settlement records for transparency.
  )
 */
export function subscribeVrfSettlements(callback: (data: VrfSettlementsResponse | null) => void, drawingId: string): Promise<() => Promise<void>> {
  return subscribe(`vrfSettlements/${drawingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as VrfSettlementsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to VrfSettlements at path '${`vrfSettlements/${drawingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many VrfSettlements items from collection vrfSettlements
 
  Read Operation Details: Anyone can view settlement records for transparency.
  
 */
export async function getManyVrfSettlements(filter: string = ""): Promise<VrfSettlementsResponse[]> {
  try {
    const results = await get("vrfSettlements", { prompt: filter });
    return Array.isArray(results) ? results as VrfSettlementsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfSettlements collection at path 'vrfSettlements': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfSettlements collection at vrfSettlements
 
  Read Operation Details: Anyone can view settlement records for transparency.
  
 */
export function subscribeManyVrfSettlements(callback: (data: VrfSettlementsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfSettlements", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfSettlementsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfSettlements collection at path '${"vrfSettlements"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all VrfSettlements items from collection vrfSettlements
 
  Read Operation Details: Anyone can view settlement records for transparency.
  
 */
export async function getAllVrfSettlements(filter: string = ""): Promise<VrfSettlementsResponse[]> {
  try {
    const results = await get("vrfSettlements", { prompt: filter });
    return Array.isArray(results) ? results as VrfSettlementsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfSettlements collection at path 'vrfSettlements': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfSettlements collection at vrfSettlements
 
  Read Operation Details: Anyone can view settlement records for transparency.
  
 */
export function subscribeAllVrfSettlements(callback: (data: VrfSettlementsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfSettlements", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfSettlementsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfSettlements collection at path '${"vrfSettlements"}': ${formatError(error)}`);
    }
  });
}

