// Generated by TaroBase SDK Generator: 2026-02-04T16:02:43.570Z
// Edits may be overwritten by subsequent runs!

import { get, set, subscribe, setMany as tarobaseSetMany } from '@pooflabs/web';
import { getFiles, setFile } from '@pooflabs/web';
import { PublicKey } from '@solana/web3.js';
import { runQuery } from '@pooflabs/web'; 


// --- SDK Utilities ---

/**
 * Helper function to check if a value is a Time.Now value
 */
const isServerTimeNow = (value: any): value is TimeOperation => {
  return (
    value &&
    typeof value === "object" &&
    value.operation === "time" &&
    value.value === "now"
  );
};

/**
 * Helper function to check if a value is an Increment operation
 */
const isIncrementOperation = (value: any): value is IncrementOperation => {
  return (
    value &&
    typeof value === "object" &&
    value.operation === "increment" &&
    typeof value.value === "number"
  );
};

/**
 * Time utility for server-time values
 *
 * Use this when you want to store the current server time in a numeric field
 *
 * Example:
 * // For a schema with { createdAt: "Int" } or { createdAt: "UInt" }
 * await setPost("123", {
 *   title: "My Post",
 *   createdAt: Time.Now  // Will be stored as the server's current timestamp
 * });
 */
export interface TimeOperation {
  operation: string;
  value: string;
}

/**
 * Increment utility for incrementing/decrementing numeric fields
 *
 * Use this when you want to increment or decrement a numeric field by a specific amount
 *
 * Example:
 * // For a schema with { viewCount: "UInt" } or { balance: "Int" }
 * await updatePost("123", {
 *   viewCount: Increment.by(1)  // Increments viewCount by 1
 * });
 * await updateAccount("456", {
 *   balance: Increment.by(-50)  // Decrements balance by 50
 * });
 */
export interface IncrementOperation {
  operation: string;
  value: number;
}

export type TokenName = 'USDC' | 'SOL' | 'pSOL' | 'other';
export interface TokenAmount {
  type: 'token';
  name: TokenName;
  amount: number; // User-friendly amount (e.g., 10.5 SOL)
}

/**
 * AddressType represents a Solana public key for use in request data.
 */
export interface AddressType {
  type: 'address';
  publicKey: PublicKey | string;
}

/**
 * Helper function to check if a value is a TokenAmount value
 */
const isTokenAmount = (value: any): value is TokenAmount => {
  return value && typeof value === 'object' && value.type === 'token';
};

/**
 * Helper function to check if a value is an AddressType value
 */
const isAddressType = (value: any): value is AddressType => {
    // Check for the 'address' type property and that publicKey is an instance of PublicKey
    return value && typeof value === 'object' && value.type === 'address';
};


/**
 * Transforms special values (Time.now, Token.amount, Address.publicKey) in an object
 * to the format expected by the backend before sending the request.
 * This function is recursive and handles nested objects and arrays.
 */
const transformValues = (data: any): any => {
  // Handle null or non-object/array types directly
  if (!data || typeof data !== 'object') {
    return data;
  }

  // Check for specific object types first using type guards
  if (isServerTimeNow(data)) {
    // Pass Time.Now object as is; backend interprets it
    return { operation: 'time', value: 'now' };
  } else if (isIncrementOperation(data)) {
    // Pass Increment operation as is; backend interprets it
    return { operation: 'increment', value: data.value };
  } else if (isTokenAmount(data)) {
    // Convert user-friendly amount to backend's integer format based on decimals
    const { name, amount } = data; // Safe access due to type guard
    if (name === 'USDC') {
      return Math.round(amount * 10 ** 6); // 6 decimals for USDC
    } else if (name === 'SOL' || name === 'pSOL') {
      return Math.round(amount * 10 ** 9); // 9 decimals for SOL
    } else {
      // Assume a default of 6 decimals for custom tokens
      return Math.round(amount * 10 ** 6);
    }
  } else if (isAddressType(data)) {
     // Convert AddressType to its base58 string representation for the backend
     if (typeof data.publicKey === 'string') {
      return data.publicKey;
     } else {
      return data.publicKey.toBase58(); // Safe access due to type guard
     }
  }

  // Handle arrays: recursively transform each item
  if (Array.isArray(data)) {
    // Use map with explicit typing for clarity
    return data.map((item: any) => transformValues(item));
  }

  // Handle regular objects: recursively transform each property
  // Create a new object to avoid modifying the original
  const result: Record<string, any> = {};
  for (const key in data) {
    // Use safer check for own properties
    if (Object.prototype.hasOwnProperty.call(data, key)) {
      result[key] = transformValues(data[key]);
    }
  }
  return result;
};

// --- SDK Helper Objects ---

export const Token: {
  /**
   * Creates a TokenAmount object representing a specific amount of a token.
   * @param name The name of the token (e.g., 'USDC', 'SOL', 'pSOL').
   * @param amount The user-friendly amount (e.g., 10.5 for 10.5 USDC).
   */
  amount: (name: TokenName, amount: number) => TokenAmount;
  /**
   * Converts a TokenAmount object back to its integer representation based on decimals.
   * Useful if you need the raw integer value on the client side.
   */
  convert: (amount: TokenAmount) => number;
} = {
  amount: (name: TokenName, amount: number): TokenAmount => ({
    type: 'token',
    name,
    amount,
  }),
  convert: (amount: TokenAmount): number => {
    // This logic mirrors the transformation in transformValues
    if (amount.name === 'USDC') {
      return Math.round(amount.amount * 10 ** 6);
    } else if (amount.name === 'SOL' || amount.name === 'pSOL') {
      return Math.round(amount.amount * 10 ** 9);
    }
    return Math.round(amount.amount * 10 ** 6); // Default or handle 'other'
  },
};

export const Time: {
  /**
   * Represents the server's current time. Use this value for 'Int' or 'UInt' fields
   * in request data where you want the server to insert the timestamp.
   */
  Now: TimeOperation;
} = {
  Now: { operation: "time", value: "now" }
};

export const Increment: {
  /**
   * Creates an increment/decrement operation for numeric fields.
   * Use positive values to increment, negative values to decrement.
   * @param value The amount to increment (positive) or decrement (negative)
   *
   * Example:
   * // Increment a counter by 1
   * await updatePost("123", { viewCount: Increment.by(1) });
   *
   * // Decrement a balance by 50
   * await updateAccount("456", { balance: Increment.by(-50) });
   */
  by: (value: number) => IncrementOperation;
} = {
  by: (value: number): IncrementOperation => ({
    operation: "increment",
    value
  })
};

export const Address: {
  /**
   * Creates an AddressType object from a PublicKey instance or a base58 string.
   * Validates the input including cryptographic on-curve check and throws an error if invalid.
   * Special case: 'solana' is allowed as a reserved string representing native SOL.
   * @param key A PublicKey instance, a base58 encoded public key string, or 'solana' for native SOL.
   */
  publicKey: (key: PublicKey | string) => AddressType;
} = {
  publicKey: (key: PublicKey | string): AddressType => {
    if (typeof key === 'string') {
      // Special case: 'solana' represents native SOL asset
      if (key === 'solana') {
        return {
          type: 'address',
          publicKey: 'solana',
        };
      }
      // Validate format: Solana addresses are 32-44 base58 characters
      if (key.length < 32 || key.length > 44) {
        throw new Error(`Invalid Solana address length: ${key.length}. Must be 32-44 characters.`);
      }
      const base58Regex = /^[1-9A-HJ-NP-Za-km-z]+$/;
      if (!base58Regex.test(key)) {
        throw new Error(`Invalid Solana address: contains invalid characters. Must be base58 encoded.`);
      }
      try {
        // Validate and create PublicKey from string
        const pkInstance = new PublicKey(key);
        // Cryptographic validation: check if address is on the ed25519 curve
        if (!PublicKey.isOnCurve(pkInstance.toBuffer())) {
          throw new Error(`Invalid Solana address: not a valid point on the ed25519 curve.`);
        }
        return {
          type: 'address',
          publicKey: pkInstance,
        };
      } catch (e) {
        // Safer error handling
        const message = e instanceof Error ? e.message : String(e);
        console.error(`Invalid public key string provided: ${key}`, message);
        throw new Error(`Invalid public key string: ${key}. ${message}`);
      }
    } else if (key instanceof PublicKey) {
      // Validate the provided PublicKey instance is on curve
      if (!PublicKey.isOnCurve(key.toBuffer())) {
        throw new Error('Invalid Solana address: not a valid point on the ed25519 curve.');
      }
      return {
        type: 'address',
        publicKey: key,
      };
    } else {
      // Handle invalid input type
      throw new Error('Invalid input for Address.publicKey: Must be a PublicKey instance or a base58 string.');
    }
  },
};

// --- Common Interfaces ---
/**
 * Common metadata fields added by TaroBase to document responses.
 */
export interface TarobaseMetadata {
  id: string;
  tarobase_created_at: number; // epoch milliseconds
}

/**
 * Represents a file stored in TaroBase Storage.
 */
export interface FileItem {
  path: string; // Full path within storage
  url: string;  // Publicly accessible URL
}

/**
 * Represents a document operation for use with setMany.
 * Used by build functions to create properly typed operations.
 */
export interface DocumentOperation {
  path: string;
  document: any;
}

// --- Batch Operations ---

/**
 * Execute multiple document operations in a single batch.
 * @param operations Array of DocumentOperation objects created by build functions
 * @returns Promise resolving to the result of the batch operation
 */
export async function setMany(operations: DocumentOperation[]): Promise<any> {
  return await tarobaseSetMany(operations);
}

// --- Error Formatting ---

/**
 * Safely format an error for logging (avoids [object Object] in logs)
 * Handles circular references, empty messages, and non-Error objects
 * Always includes the full error object for comprehensive debugging
 */
export function formatError(error: unknown): string {
  if (error === null) return 'null';
  if (error === undefined) return 'undefined';
  if (typeof error === 'string') return error || 'Empty error string';

  // For Error instances, prepend the message for readability
  const prefix = error instanceof Error ? `${error.message?.trim() || 'No message'} | Full error: ` : '';

  try {
    // Use Object.getOwnPropertyNames to include non-enumerable properties (like Error's name, message, stack)
    const str = JSON.stringify(error, Object.getOwnPropertyNames(error), 2);
    return prefix + (str || 'Empty object');
  } catch {
    // Circular reference or other stringify error
    return prefix + 'Unserializable error';
  }
}

// --- Generated Functions by Policy Path ---

// --- Path: uploadedImages/$imageId ---

/**
 * Handles UploadedImages files (Get Single File based on its ID, null if not found)
 */
export async function getUploadedImages(imageId: string): Promise<FileItem | null> {
  try {
    const rawResult = await getFiles(`uploadedImages/${imageId}`);
    if (!rawResult || !Array.isArray(rawResult) || rawResult.length === 0) return null;
    return rawResult[0] as FileItem;
  } catch (error) {
    console.error(`Error getting file UploadedImages: ${formatError(error)}`);
    return null;
  }
}

/**
 * Handles UploadedImages files (Upload/Replace a File and persist it keyed by its ID) To get the file URL use the getUploadedImages function right after this one.
 * @returns A boolean indicating whether the upload succeeded (true) or failed (false). Always check this value to confirm the upload worked.
 */
export async function uploadUploadedImages(imageId: string, file: File): Promise<boolean> {
  try {
    const pathUsed = `uploadedImages/${imageId}`;
    const result = await setFile(pathUsed, file);
    return !!result;
  } catch (error) {
    console.error(`Error uploading file UploadedImages: ${formatError(error)}`);
    return false;
  }
}

/**
 * Handles UploadedImages files (Delete File based on its ID)
 * @returns A boolean indicating whether the delete succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteUploadedImages(imageId: string): Promise<boolean> {
  try {
    await setFile(`uploadedImages/${imageId}`, null);
    return true;
  } catch (error) {
    console.error(`Error deleting file UploadedImages: ${formatError(error)}`);
    return false;
  }
}

// --- Path: commonQueries/$queryId ---

export interface CommonQueriesRequest {

}

export interface CommonQueriesResponse {

  id: string;
  tarobase_created_at: number;
}

/**
 * 
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
   (Get Single Item)
 */
export async function getCommonQueries(queryId: string): Promise<CommonQueriesResponse | null> {
  try {
    const result = await get(`commonQueries/${queryId}`);
    return result as CommonQueriesResponse | null;
  } catch (error) {
    console.error(`Error getting CommonQueries: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single CommonQueries document. (
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
  )
 */
export function subscribeCommonQueries(callback: (data: CommonQueriesResponse | null) => void, queryId: string): Promise<() => Promise<void>> {
  return subscribe(`commonQueries/${queryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as CommonQueriesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to CommonQueries at path '${`commonQueries/${queryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many CommonQueries items from collection commonQueries
 
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
  
 */
export async function getManyCommonQueries(filter: string = ""): Promise<CommonQueriesResponse[]> {
  try {
    const results = await get("commonQueries", { prompt: filter });
    return Array.isArray(results) ? results as CommonQueriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting CommonQueries collection at path 'commonQueries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in CommonQueries collection at commonQueries
 
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
  
 */
export function subscribeManyCommonQueries(callback: (data: CommonQueriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("commonQueries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as CommonQueriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to CommonQueries collection at path '${"commonQueries"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all CommonQueries items from collection commonQueries
 
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
  
 */
export async function getAllCommonQueries(filter: string = ""): Promise<CommonQueriesResponse[]> {
  try {
    const results = await get("commonQueries", { prompt: filter });
    return Array.isArray(results) ? results as CommonQueriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting CommonQueries collection at path 'commonQueries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in CommonQueries collection at commonQueries
 
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
  
 */
export function subscribeAllCommonQueries(callback: (data: CommonQueriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("commonQueries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as CommonQueriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to CommonQueries collection at path '${"commonQueries"}': ${formatError(error)}`);
    }
  });
}

/** Arguments accepted by the "solBalance" query on CommonQueries. */
interface CommonQueriesSolBalanceArgs {
  walletAddress: string;
}

/**
 * Runs the "solBalance" query on CommonQueries.
 * Description: Get SOL balance for a wallet address in lamports (1 SOL = 1,000,000,000 lamports). Pass walletAddress as parameter.
 * Query Logic: @TokenPlugin.getBalance(@newData.walletAddress, @constants.SOL)
 */
export async function runSolBalanceQueryForCommonQueries(queryId: string, args: CommonQueriesSolBalanceArgs): Promise<number> {
  try {
    const result = await runQuery(`commonQueries/${queryId}`, "solBalance", args);
    return result as number;
  } catch (error) {
    console.error(`Error running query "solBalance" on CommonQueries: ${formatError(error)}`);
    throw error;
  }
}

/** Arguments accepted by the "usdcBalance" query on CommonQueries. */
interface CommonQueriesUsdcBalanceArgs {
  walletAddress: string;
}

/**
 * Runs the "usdcBalance" query on CommonQueries.
 * Description: Get USDC balance for a wallet address in base units (1 USDC = 1,000,000 base units with 6 decimals). Pass walletAddress as parameter.
 * Query Logic: @TokenPlugin.getBalance(@newData.walletAddress, @constants.USDC)
 */
export async function runUsdcBalanceQueryForCommonQueries(queryId: string, args: CommonQueriesUsdcBalanceArgs): Promise<number> {
  try {
    const result = await runQuery(`commonQueries/${queryId}`, "usdcBalance", args);
    return result as number;
  } catch (error) {
    console.error(`Error running query "usdcBalance" on CommonQueries: ${formatError(error)}`);
    throw error;
  }
}

/** Arguments accepted by the "tokenBalance" query on CommonQueries. */
interface CommonQueriesTokenBalanceArgs {
  walletAddress: string;
  tokenMint: string;
}

/**
 * Runs the "tokenBalance" query on CommonQueries.
 * Description: Get balance for any SPL token mint for a wallet address. Pass walletAddress and tokenMint as parameters. Returns balance in the token's smallest units based on its decimals.
 * Query Logic: @TokenPlugin.getBalance(@newData.walletAddress, @newData.tokenMint)
 */
export async function runTokenBalanceQueryForCommonQueries(queryId: string, args: CommonQueriesTokenBalanceArgs): Promise<number> {
  try {
    const result = await runQuery(`commonQueries/${queryId}`, "tokenBalance", args);
    return result as number;
  } catch (error) {
    console.error(`Error running query "tokenBalance" on CommonQueries: ${formatError(error)}`);
    throw error;
  }
}

/** Arguments accepted by the "jupiterSwapQuote" query on CommonQueries. */
interface CommonQueriesJupiterSwapQuoteArgs {
  inputMint: string;
  outputMint: string;
  amount: string;
}

/**
 * Runs the "jupiterSwapQuote" query on CommonQueries.
 * Description: Get a Jupiter swap quote for exchanging tokens. Pass inputMint (token to sell, use @constants.SOL for native SOL), outputMint (token to buy), and amount (in smallest units like lamports). Returns the expected output amount.
 * Query Logic: @DeFiPlugin.getSwapQuote(@newData.inputMint, @newData.outputMint, @newData.amount)
 */
export async function runJupiterSwapQuoteQueryForCommonQueries(queryId: string, args: CommonQueriesJupiterSwapQuoteArgs): Promise<number> {
  try {
    const result = await runQuery(`commonQueries/${queryId}`, "jupiterSwapQuote", args);
    return result as number;
  } catch (error) {
    console.error(`Error running query "jupiterSwapQuote" on CommonQueries: ${formatError(error)}`);
    throw error;
  }
}

/** Arguments accepted by the "meteoraSwapQuote" query on CommonQueries. */
interface CommonQueriesMeteoraSwapQuoteArgs {
  tokenMintAddress: string;
  tokenToSwapInMintAddress: string;
  tokenAmount: string;
}

/**
 * Runs the "meteoraSwapQuote" query on CommonQueries.
 * Description: Get a Meteora dynamic bonding curve swap quote. Pass tokenMintAddress (the pool's base token), tokenToSwapInMintAddress (token to swap in, use @constants.SOL for native SOL), and tokenAmount (in smallest units). Returns the expected output amount.
 * Query Logic: @DeFiPlugin.getMeteoraSwapQuote(@newData.tokenMintAddress, @newData.tokenToSwapInMintAddress, @newData.tokenAmount)
 */
export async function runMeteoraSwapQuoteQueryForCommonQueries(queryId: string, args: CommonQueriesMeteoraSwapQuoteArgs): Promise<number> {
  try {
    const result = await runQuery(`commonQueries/${queryId}`, "meteoraSwapQuote", args);
    return result as number;
  } catch (error) {
    console.error(`Error running query "meteoraSwapQuote" on CommonQueries: ${formatError(error)}`);
    throw error;
  }
}

// --- Path: jackpot/$jackpotId ---

export interface JackpotRequest {
  balance: number | TimeOperation | IncrementOperation | TokenAmount;
  nextDrawingAt: number | TimeOperation | IncrementOperation | TokenAmount;
  drawingNumber: number | TimeOperation | IncrementOperation | TokenAmount;
  isOver200Sol: boolean;
  lastUpdatedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface JackpotResponse {
  balance: number;
  nextDrawingAt: number;
  drawingNumber: number;
  isOver200Sol: boolean;
  lastUpdatedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Jackpot operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildJackpot(jackpotId: string, data: JackpotRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `jackpot/${jackpotId}`, document: doc };
}

/**
 * Anyone can create the jackpot document for stress testing. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setJackpot(jackpotId: string, data: JackpotRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`jackpot/${jackpotId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Jackpot: ${formatError(error)}`);
    return false;
  }
}

export type JackpotRequestUpdate = Partial<JackpotRequest>;

/**
 * Build a Jackpot update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateJackpot(jackpotId: string, data: JackpotRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `jackpot/${jackpotId}`, document: doc };
}

/**
 * Anyone can update balance, nextDrawingAt, drawingNumber, and isOver200Sol flag for stress testing. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateJackpot(jackpotId: string, data: JackpotRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`jackpot/${jackpotId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Jackpot: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
   (Get Single Item)
 */
export async function getJackpot(jackpotId: string): Promise<JackpotResponse | null> {
  try {
    const result = await get(`jackpot/${jackpotId}`);
    return result as JackpotResponse | null;
  } catch (error) {
    console.error(`Error getting Jackpot: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Jackpot document. (
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
  )
 */
export function subscribeJackpot(callback: (data: JackpotResponse | null) => void, jackpotId: string): Promise<() => Promise<void>> {
  return subscribe(`jackpot/${jackpotId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as JackpotResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Jackpot at path '${`jackpot/${jackpotId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Jackpot items from collection jackpot
 
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
  
 */
export async function getManyJackpot(filter: string = ""): Promise<JackpotResponse[]> {
  try {
    const results = await get("jackpot", { prompt: filter });
    return Array.isArray(results) ? results as JackpotResponse[] : [];
  } catch (error) {
    console.error(`Error getting Jackpot collection at path 'jackpot': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Jackpot collection at jackpot
 
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
  
 */
export function subscribeManyJackpot(callback: (data: JackpotResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("jackpot", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as JackpotResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Jackpot collection at path '${"jackpot"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Jackpot items from collection jackpot
 
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
  
 */
export async function getAllJackpot(filter: string = ""): Promise<JackpotResponse[]> {
  try {
    const results = await get("jackpot", { prompt: filter });
    return Array.isArray(results) ? results as JackpotResponse[] : [];
  } catch (error) {
    console.error(`Error getting Jackpot collection at path 'jackpot': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Jackpot collection at jackpot
 
  Read Operation Details: Anyone can read jackpot state to see current balance, next drawing time, and drawing count.
  
 */
export function subscribeAllJackpot(callback: (data: JackpotResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("jackpot", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as JackpotResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Jackpot collection at path '${"jackpot"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Anyone can delete the jackpot document for stress testing.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteJackpot(jackpotId: string): Promise<boolean> {
  try {
    const succeeded = await set(`jackpot/${jackpotId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Jackpot: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Jackpot for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteJackpot(jackpotId: string): DocumentOperation {
  return { path: `jackpot/${jackpotId}`, document: null };
}

// --- Path: drawings/$drawingId ---

export interface DrawingsRequest {
  status: string;
  endTime?: number | TimeOperation | IncrementOperation | TokenAmount;
  jackpot?: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface DrawingsResponse {
  status: string;
  endTime?: number;
  jackpot?: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Drawings operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDrawings(drawingId: string, data: DrawingsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `drawings/${drawingId}`, document: doc };
}

/**
 * Anyone can create a drawing for stress testing. Set status to 'active' for new drawings. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setDrawings(drawingId: string, data: DrawingsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`drawings/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Drawings: ${formatError(error)}`);
    return false;
  }
}

export type DrawingsRequestUpdate = Partial<DrawingsRequest>;

/**
 * Build a Drawings update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateDrawings(drawingId: string, data: DrawingsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `drawings/${drawingId}`, document: doc };
}

/**
 * Anyone can update drawing status (active to completed) and add results for stress testing. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateDrawings(drawingId: string, data: DrawingsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`drawings/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Drawings: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
   (Get Single Item)
 */
export async function getDrawings(drawingId: string): Promise<DrawingsResponse | null> {
  try {
    const result = await get(`drawings/${drawingId}`);
    return result as DrawingsResponse | null;
  } catch (error) {
    console.error(`Error getting Drawings: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Drawings document. (
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
  )
 */
export function subscribeDrawings(callback: (data: DrawingsResponse | null) => void, drawingId: string): Promise<() => Promise<void>> {
  return subscribe(`drawings/${drawingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as DrawingsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Drawings at path '${`drawings/${drawingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Drawings items from collection drawings
 
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
  
 */
export async function getManyDrawings(filter: string = ""): Promise<DrawingsResponse[]> {
  try {
    const results = await get("drawings", { prompt: filter });
    return Array.isArray(results) ? results as DrawingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Drawings collection at path 'drawings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Drawings collection at drawings
 
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
  
 */
export function subscribeManyDrawings(callback: (data: DrawingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("drawings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as DrawingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Drawings collection at path '${"drawings"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Drawings items from collection drawings
 
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
  
 */
export async function getAllDrawings(filter: string = ""): Promise<DrawingsResponse[]> {
  try {
    const results = await get("drawings", { prompt: filter });
    return Array.isArray(results) ? results as DrawingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Drawings collection at path 'drawings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Drawings collection at drawings
 
  Read Operation Details: Anyone can read drawings to see active drawings and past results.
  
 */
export function subscribeAllDrawings(callback: (data: DrawingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("drawings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as DrawingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Drawings collection at path '${"drawings"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Anyone can delete drawings for stress testing.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteDrawings(drawingId: string): Promise<boolean> {
  try {
    const succeeded = await set(`drawings/${drawingId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Drawings: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Drawings for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteDrawings(drawingId: string): DocumentOperation {
  return { path: `drawings/${drawingId}`, document: null };
}

// --- Path: entries/$entryId ---

export interface EntriesRequest {
  wallet: AddressType;
  drawingId: string;
  tokenBalance: number | TimeOperation | IncrementOperation | TokenAmount;
  enteredAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface EntriesResponse {
  wallet: string;
  drawingId: string;
  tokenBalance: number;
  enteredAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Entries operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildEntries(entryId: string, data: EntriesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `entries/${entryId}`, document: doc };
}

/**
 * Anyone can create entries (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setEntries(entryId: string, data: EntriesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`entries/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Entries: ${formatError(error)}`);
    return false;
  }
}

export type EntriesRequestUpdate = Partial<EntriesRequest>;

/**
 * Build a Entries update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateEntries(entryId: string, data: EntriesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `entries/${entryId}`, document: doc };
}

/**
 * Anyone can update entries (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateEntries(entryId: string, data: EntriesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`entries/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Entries: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read entries
   (Get Single Item)
 */
export async function getEntries(entryId: string): Promise<EntriesResponse | null> {
  try {
    const result = await get(`entries/${entryId}`);
    return result as EntriesResponse | null;
  } catch (error) {
    console.error(`Error getting Entries: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Entries document. (
  Read Operation Details: Anyone can read entries
  )
 */
export function subscribeEntries(callback: (data: EntriesResponse | null) => void, entryId: string): Promise<() => Promise<void>> {
  return subscribe(`entries/${entryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as EntriesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Entries at path '${`entries/${entryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Entries items from collection entries
 
  Read Operation Details: Anyone can read entries
  
 */
export async function getManyEntries(filter: string = ""): Promise<EntriesResponse[]> {
  try {
    const results = await get("entries", { prompt: filter });
    return Array.isArray(results) ? results as EntriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Entries collection at path 'entries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Entries collection at entries
 
  Read Operation Details: Anyone can read entries
  
 */
export function subscribeManyEntries(callback: (data: EntriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("entries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as EntriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Entries collection at path '${"entries"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Entries items from collection entries
 
  Read Operation Details: Anyone can read entries
  
 */
export async function getAllEntries(filter: string = ""): Promise<EntriesResponse[]> {
  try {
    const results = await get("entries", { prompt: filter });
    return Array.isArray(results) ? results as EntriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Entries collection at path 'entries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Entries collection at entries
 
  Read Operation Details: Anyone can read entries
  
 */
export function subscribeAllEntries(callback: (data: EntriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("entries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as EntriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Entries collection at path '${"entries"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Anyone can delete entries
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteEntries(entryId: string): Promise<boolean> {
  try {
    const succeeded = await set(`entries/${entryId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Entries: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Entries for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteEntries(entryId: string): DocumentOperation {
  return { path: `entries/${entryId}`, document: null };
}

// --- Path: jackpotDeposits/$depositId ---

export interface JackpotDepositsRequest {
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
  depositedBy: AddressType;
  depositedAt: number | TimeOperation | IncrementOperation | TokenAmount;
  note?: string;
}

export interface JackpotDepositsResponse {
  amount: number;
  depositedBy: string;
  depositedAt: number;
  note?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a JackpotDeposits operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildJackpotDeposits(depositId: string, data: JackpotDepositsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `jackpotDeposits/${depositId}`, document: doc };
}

/**
 * Admin deposits SOL to fund the jackpot. For testing phase, this is manual. Later will be automated via buy/sell tax. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setJackpotDeposits(depositId: string, data: JackpotDepositsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`jackpotDeposits/${depositId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting JackpotDeposits: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view deposit history for transparency.
   (Get Single Item)
 */
export async function getJackpotDeposits(depositId: string): Promise<JackpotDepositsResponse | null> {
  try {
    const result = await get(`jackpotDeposits/${depositId}`);
    return result as JackpotDepositsResponse | null;
  } catch (error) {
    console.error(`Error getting JackpotDeposits: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single JackpotDeposits document. (
  Read Operation Details: Anyone can view deposit history for transparency.
  )
 */
export function subscribeJackpotDeposits(callback: (data: JackpotDepositsResponse | null) => void, depositId: string): Promise<() => Promise<void>> {
  return subscribe(`jackpotDeposits/${depositId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as JackpotDepositsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to JackpotDeposits at path '${`jackpotDeposits/${depositId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many JackpotDeposits items from collection jackpotDeposits
 
  Read Operation Details: Anyone can view deposit history for transparency.
  
 */
export async function getManyJackpotDeposits(filter: string = ""): Promise<JackpotDepositsResponse[]> {
  try {
    const results = await get("jackpotDeposits", { prompt: filter });
    return Array.isArray(results) ? results as JackpotDepositsResponse[] : [];
  } catch (error) {
    console.error(`Error getting JackpotDeposits collection at path 'jackpotDeposits': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in JackpotDeposits collection at jackpotDeposits
 
  Read Operation Details: Anyone can view deposit history for transparency.
  
 */
export function subscribeManyJackpotDeposits(callback: (data: JackpotDepositsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("jackpotDeposits", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as JackpotDepositsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to JackpotDeposits collection at path '${"jackpotDeposits"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all JackpotDeposits items from collection jackpotDeposits
 
  Read Operation Details: Anyone can view deposit history for transparency.
  
 */
export async function getAllJackpotDeposits(filter: string = ""): Promise<JackpotDepositsResponse[]> {
  try {
    const results = await get("jackpotDeposits", { prompt: filter });
    return Array.isArray(results) ? results as JackpotDepositsResponse[] : [];
  } catch (error) {
    console.error(`Error getting JackpotDeposits collection at path 'jackpotDeposits': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in JackpotDeposits collection at jackpotDeposits
 
  Read Operation Details: Anyone can view deposit history for transparency.
  
 */
export function subscribeAllJackpotDeposits(callback: (data: JackpotDepositsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("jackpotDeposits", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as JackpotDepositsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to JackpotDeposits collection at path '${"jackpotDeposits"}': ${formatError(error)}`);
    }
  });
}

// --- Path: lotteryHouse/$houseId ---

export interface LotteryHouseRequest {
  active: boolean;
}

export interface LotteryHouseResponse {
  active: boolean;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a LotteryHouse operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildLotteryHouse(houseId: string, data?: LotteryHouseRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `lotteryHouse/${houseId}`, document: doc };
}

/**
 * Admin creates house escrow once. Creates PDA that holds SOL for lottery payouts. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setLotteryHouse(houseId: string, data?: LotteryHouseRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`lotteryHouse/${houseId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting LotteryHouse: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can check house balance and status for transparency.
   (Get Single Item)
 */
export async function getLotteryHouse(houseId: string): Promise<LotteryHouseResponse | null> {
  try {
    const result = await get(`lotteryHouse/${houseId}`);
    return result as LotteryHouseResponse | null;
  } catch (error) {
    console.error(`Error getting LotteryHouse: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single LotteryHouse document. (
  Read Operation Details: Anyone can check house balance and status for transparency.
  )
 */
export function subscribeLotteryHouse(callback: (data: LotteryHouseResponse | null) => void, houseId: string): Promise<() => Promise<void>> {
  return subscribe(`lotteryHouse/${houseId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as LotteryHouseResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to LotteryHouse at path '${`lotteryHouse/${houseId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many LotteryHouse items from collection lotteryHouse
 
  Read Operation Details: Anyone can check house balance and status for transparency.
  
 */
export async function getManyLotteryHouse(filter: string = ""): Promise<LotteryHouseResponse[]> {
  try {
    const results = await get("lotteryHouse", { prompt: filter });
    return Array.isArray(results) ? results as LotteryHouseResponse[] : [];
  } catch (error) {
    console.error(`Error getting LotteryHouse collection at path 'lotteryHouse': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in LotteryHouse collection at lotteryHouse
 
  Read Operation Details: Anyone can check house balance and status for transparency.
  
 */
export function subscribeManyLotteryHouse(callback: (data: LotteryHouseResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("lotteryHouse", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as LotteryHouseResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to LotteryHouse collection at path '${"lotteryHouse"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all LotteryHouse items from collection lotteryHouse
 
  Read Operation Details: Anyone can check house balance and status for transparency.
  
 */
export async function getAllLotteryHouse(filter: string = ""): Promise<LotteryHouseResponse[]> {
  try {
    const results = await get("lotteryHouse", { prompt: filter });
    return Array.isArray(results) ? results as LotteryHouseResponse[] : [];
  } catch (error) {
    console.error(`Error getting LotteryHouse collection at path 'lotteryHouse': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in LotteryHouse collection at lotteryHouse
 
  Read Operation Details: Anyone can check house balance and status for transparency.
  
 */
export function subscribeAllLotteryHouse(callback: (data: LotteryHouseResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("lotteryHouse", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as LotteryHouseResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to LotteryHouse collection at path '${"lotteryHouse"}': ${formatError(error)}`);
    }
  });
}

/**
 * Runs the "getHouseBalance" query on LotteryHouse.
 * Query Logic: @TokenPlugin.getBalance(@constants.LOTTERY_HOUSE_ID, @constants.SOL)
 */
export async function runGetHouseBalanceQueryForLotteryHouse(houseId: string, ): Promise<number> {
  try {
    const result = await runQuery(`lotteryHouse/${houseId}`, "getHouseBalance", {});
    return result as number;
  } catch (error) {
    console.error(`Error running query "getHouseBalance" on LotteryHouse: ${formatError(error)}`);
    throw error;
  }
}

// --- Path: houseFunding/$fundingId ---

export interface HouseFundingRequest {
  amt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface HouseFundingResponse {
  amt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a HouseFunding operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildHouseFunding(fundingId: string, data?: HouseFundingRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `houseFunding/${fundingId}`, document: doc };
}

/**
 * Admin deposits SOL to fund house for lottery payouts. Transfers SOL from admin to house PDA. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setHouseFunding(fundingId: string, data?: HouseFundingRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`houseFunding/${fundingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting HouseFunding: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view funding history for transparency.
   (Get Single Item)
 */
export async function getHouseFunding(fundingId: string): Promise<HouseFundingResponse | null> {
  try {
    const result = await get(`houseFunding/${fundingId}`);
    return result as HouseFundingResponse | null;
  } catch (error) {
    console.error(`Error getting HouseFunding: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single HouseFunding document. (
  Read Operation Details: Anyone can view funding history for transparency.
  )
 */
export function subscribeHouseFunding(callback: (data: HouseFundingResponse | null) => void, fundingId: string): Promise<() => Promise<void>> {
  return subscribe(`houseFunding/${fundingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as HouseFundingResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to HouseFunding at path '${`houseFunding/${fundingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many HouseFunding items from collection houseFunding
 
  Read Operation Details: Anyone can view funding history for transparency.
  
 */
export async function getManyHouseFunding(filter: string = ""): Promise<HouseFundingResponse[]> {
  try {
    const results = await get("houseFunding", { prompt: filter });
    return Array.isArray(results) ? results as HouseFundingResponse[] : [];
  } catch (error) {
    console.error(`Error getting HouseFunding collection at path 'houseFunding': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in HouseFunding collection at houseFunding
 
  Read Operation Details: Anyone can view funding history for transparency.
  
 */
export function subscribeManyHouseFunding(callback: (data: HouseFundingResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("houseFunding", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as HouseFundingResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to HouseFunding collection at path '${"houseFunding"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all HouseFunding items from collection houseFunding
 
  Read Operation Details: Anyone can view funding history for transparency.
  
 */
export async function getAllHouseFunding(filter: string = ""): Promise<HouseFundingResponse[]> {
  try {
    const results = await get("houseFunding", { prompt: filter });
    return Array.isArray(results) ? results as HouseFundingResponse[] : [];
  } catch (error) {
    console.error(`Error getting HouseFunding collection at path 'houseFunding': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in HouseFunding collection at houseFunding
 
  Read Operation Details: Anyone can view funding history for transparency.
  
 */
export function subscribeAllHouseFunding(callback: (data: HouseFundingResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("houseFunding", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as HouseFundingResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to HouseFunding collection at path '${"houseFunding"}': ${formatError(error)}`);
    }
  });
}

// --- Path: vrfDrawings/$drawingId ---

export interface VrfDrawingsRequest {
  drawNum: number | TimeOperation | IncrementOperation | TokenAmount;
  jackpot: number | TimeOperation | IncrementOperation | TokenAmount;
  entries: number | TimeOperation | IncrementOperation | TokenAmount;
  result?: number | TimeOperation | IncrementOperation | TokenAmount;
  winner?: AddressType;
  payout?: number | TimeOperation | IncrementOperation | TokenAmount;
  settled?: boolean;
  payoutTxHash?: string;
  evenOddResult?: string;
  scheduledRevealAt?: number | TimeOperation | IncrementOperation | TokenAmount;
  actualRevealAt?: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface VrfDrawingsResponse {
  drawNum: number;
  jackpot: number;
  entries: number;
  result?: number;
  winner?: string;
  payout?: number;
  settled?: boolean;
  payoutTxHash?: string;
  evenOddResult?: string;
  scheduledRevealAt?: number;
  actualRevealAt?: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a VrfDrawings operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildVrfDrawings(drawingId: string, data?: VrfDrawingsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `vrfDrawings/${drawingId}`, document: doc };
}

/**
 * Admin triggers a lottery drawing. Requests VRF randomness. Drawing ID should be unique (e.g., draw_1, draw_2). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setVrfDrawings(drawingId: string, data?: VrfDrawingsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`vrfDrawings/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting VrfDrawings: ${formatError(error)}`);
    return false;
  }
}

export type VrfDrawingsRequestUpdate = Partial<VrfDrawingsRequest>;

/**
 * Build a VrfDrawings update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateVrfDrawings(drawingId: string, data: VrfDrawingsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `vrfDrawings/${drawingId}`, document: doc };
}

/**
 * Admin or oracle callback updates drawing with result, winner, and payout after VRF reveals. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateVrfDrawings(drawingId: string, data: VrfDrawingsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`vrfDrawings/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating VrfDrawings: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
   (Get Single Item)
 */
export async function getVrfDrawings(drawingId: string): Promise<VrfDrawingsResponse | null> {
  try {
    const result = await get(`vrfDrawings/${drawingId}`);
    return result as VrfDrawingsResponse | null;
  } catch (error) {
    console.error(`Error getting VrfDrawings: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single VrfDrawings document. (
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
  )
 */
export function subscribeVrfDrawings(callback: (data: VrfDrawingsResponse | null) => void, drawingId: string): Promise<() => Promise<void>> {
  return subscribe(`vrfDrawings/${drawingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as VrfDrawingsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to VrfDrawings at path '${`vrfDrawings/${drawingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many VrfDrawings items from collection vrfDrawings
 
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
  
 */
export async function getManyVrfDrawings(filter: string = ""): Promise<VrfDrawingsResponse[]> {
  try {
    const results = await get("vrfDrawings", { prompt: filter });
    return Array.isArray(results) ? results as VrfDrawingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfDrawings collection at path 'vrfDrawings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfDrawings collection at vrfDrawings
 
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
  
 */
export function subscribeManyVrfDrawings(callback: (data: VrfDrawingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfDrawings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfDrawingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfDrawings collection at path '${"vrfDrawings"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all VrfDrawings items from collection vrfDrawings
 
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
  
 */
export async function getAllVrfDrawings(filter: string = ""): Promise<VrfDrawingsResponse[]> {
  try {
    const results = await get("vrfDrawings", { prompt: filter });
    return Array.isArray(results) ? results as VrfDrawingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfDrawings collection at path 'vrfDrawings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfDrawings collection at vrfDrawings
 
  Read Operation Details: Anyone can view drawing details. result=null means pending VRF fulfillment.
  
 */
export function subscribeAllVrfDrawings(callback: (data: VrfDrawingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfDrawings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfDrawingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfDrawings collection at path '${"vrfDrawings"}': ${formatError(error)}`);
    }
  });
}

/**
 * Runs the "getVRFAddress" query on VrfDrawings.
 * Query Logic: @OraclePlugin.getVRFAddress($drawingId)
 */
export async function runGetVRFAddressQueryForVrfDrawings(drawingId: string, ): Promise<string> {
  try {
    const result = await runQuery(`vrfDrawings/${drawingId}`, "getVRFAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getVRFAddress" on VrfDrawings: ${formatError(error)}`);
    throw error;
  }
}

// --- Path: vrfReveals/$drawingId ---

export interface VrfRevealsRequest {

}

export interface VrfRevealsResponse {

  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a VrfReveals operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildVrfReveals(drawingId: string, data?: VrfRevealsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `vrfReveals/${drawingId}`, document: doc };
}

/**
 * Oracle callback. Reads random number in range [0, entries), updates drawing with result. Winner selection done offchain based on result index. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setVrfReveals(drawingId: string, data?: VrfRevealsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`vrfReveals/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting VrfReveals: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
   (Get Single Item)
 */
export async function getVrfReveals(drawingId: string): Promise<VrfRevealsResponse | null> {
  try {
    const result = await get(`vrfReveals/${drawingId}`);
    return result as VrfRevealsResponse | null;
  } catch (error) {
    console.error(`Error getting VrfReveals: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single VrfReveals document. (
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
  )
 */
export function subscribeVrfReveals(callback: (data: VrfRevealsResponse | null) => void, drawingId: string): Promise<() => Promise<void>> {
  return subscribe(`vrfReveals/${drawingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as VrfRevealsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to VrfReveals at path '${`vrfReveals/${drawingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many VrfReveals items from collection vrfReveals
 
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
  
 */
export async function getManyVrfReveals(filter: string = ""): Promise<VrfRevealsResponse[]> {
  try {
    const results = await get("vrfReveals", { prompt: filter });
    return Array.isArray(results) ? results as VrfRevealsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfReveals collection at path 'vrfReveals': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfReveals collection at vrfReveals
 
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
  
 */
export function subscribeManyVrfReveals(callback: (data: VrfRevealsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfReveals", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfRevealsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfReveals collection at path '${"vrfReveals"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all VrfReveals items from collection vrfReveals
 
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
  
 */
export async function getAllVrfReveals(filter: string = ""): Promise<VrfRevealsResponse[]> {
  try {
    const results = await get("vrfReveals", { prompt: filter });
    return Array.isArray(results) ? results as VrfRevealsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfReveals collection at path 'vrfReveals': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfReveals collection at vrfReveals
 
  Read Operation Details: Anyone can view reveal records to verify VRF execution.
  
 */
export function subscribeAllVrfReveals(callback: (data: VrfRevealsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfReveals", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfRevealsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfReveals collection at path '${"vrfReveals"}': ${formatError(error)}`);
    }
  });
}

// --- Path: vrfEntries/$entryId ---

export interface VrfEntriesRequest {
  drawId: string;
  wallet: AddressType;
  idx: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface VrfEntriesResponse {
  drawId: string;
  wallet: string;
  idx: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a VrfEntries operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildVrfEntries(entryId: string, data?: VrfEntriesRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `vrfEntries/${entryId}`, document: doc };
}

/**
 * Anyone holding at least MIN_HOLDING_TOKENS (1000 tokens with 9 decimals) of PEPEBALL can register as entry. Entry ID should be drawId_wallet format. idx is the entry index (0-based) for winner selection. Validates user holds minimum PEPEBALL balance before allowing entry. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setVrfEntries(entryId: string, data?: VrfEntriesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`vrfEntries/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting VrfEntries: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
   (Get Single Item)
 */
export async function getVrfEntries(entryId: string): Promise<VrfEntriesResponse | null> {
  try {
    const result = await get(`vrfEntries/${entryId}`);
    return result as VrfEntriesResponse | null;
  } catch (error) {
    console.error(`Error getting VrfEntries: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single VrfEntries document. (
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
  )
 */
export function subscribeVrfEntries(callback: (data: VrfEntriesResponse | null) => void, entryId: string): Promise<() => Promise<void>> {
  return subscribe(`vrfEntries/${entryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as VrfEntriesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to VrfEntries at path '${`vrfEntries/${entryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many VrfEntries items from collection vrfEntries
 
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
  
 */
export async function getManyVrfEntries(filter: string = ""): Promise<VrfEntriesResponse[]> {
  try {
    const results = await get("vrfEntries", { prompt: filter });
    return Array.isArray(results) ? results as VrfEntriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfEntries collection at path 'vrfEntries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfEntries collection at vrfEntries
 
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
  
 */
export function subscribeManyVrfEntries(callback: (data: VrfEntriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfEntries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfEntriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfEntries collection at path '${"vrfEntries"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all VrfEntries items from collection vrfEntries
 
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
  
 */
export async function getAllVrfEntries(filter: string = ""): Promise<VrfEntriesResponse[]> {
  try {
    const results = await get("vrfEntries", { prompt: filter });
    return Array.isArray(results) ? results as VrfEntriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfEntries collection at path 'vrfEntries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfEntries collection at vrfEntries
 
  Read Operation Details: Anyone can view entries to verify eligibility and entry order.
  
 */
export function subscribeAllVrfEntries(callback: (data: VrfEntriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfEntries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfEntriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfEntries collection at path '${"vrfEntries"}': ${formatError(error)}`);
    }
  });
}

// --- Path: feeHarvests/$harvestId ---

export interface FeeHarvestsRequest {
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
  harvestedAt: number | TimeOperation | IncrementOperation | TokenAmount;
  harvestedBy: AddressType;
  tokenMint: string;
  txSignature?: string;
}

export interface FeeHarvestsResponse {
  amount: number;
  harvestedAt: number;
  harvestedBy: string;
  tokenMint: string;
  txSignature?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a FeeHarvests operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildFeeHarvests(harvestId: string, data: FeeHarvestsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `feeHarvests/${harvestId}`, document: doc };
}

/**
 * Admin only. Records a fee harvest event with amount in smallest units (lamports), timestamp, harvester address, token mint, and optional transaction signature. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setFeeHarvests(harvestId: string, data: FeeHarvestsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`feeHarvests/${harvestId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting FeeHarvests: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
   (Get Single Item)
 */
export async function getFeeHarvests(harvestId: string): Promise<FeeHarvestsResponse | null> {
  try {
    const result = await get(`feeHarvests/${harvestId}`);
    return result as FeeHarvestsResponse | null;
  } catch (error) {
    console.error(`Error getting FeeHarvests: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single FeeHarvests document. (
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
  )
 */
export function subscribeFeeHarvests(callback: (data: FeeHarvestsResponse | null) => void, harvestId: string): Promise<() => Promise<void>> {
  return subscribe(`feeHarvests/${harvestId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as FeeHarvestsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to FeeHarvests at path '${`feeHarvests/${harvestId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many FeeHarvests items from collection feeHarvests
 
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
  
 */
export async function getManyFeeHarvests(filter: string = ""): Promise<FeeHarvestsResponse[]> {
  try {
    const results = await get("feeHarvests", { prompt: filter });
    return Array.isArray(results) ? results as FeeHarvestsResponse[] : [];
  } catch (error) {
    console.error(`Error getting FeeHarvests collection at path 'feeHarvests': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FeeHarvests collection at feeHarvests
 
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
  
 */
export function subscribeManyFeeHarvests(callback: (data: FeeHarvestsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("feeHarvests", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FeeHarvestsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FeeHarvests collection at path '${"feeHarvests"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all FeeHarvests items from collection feeHarvests
 
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
  
 */
export async function getAllFeeHarvests(filter: string = ""): Promise<FeeHarvestsResponse[]> {
  try {
    const results = await get("feeHarvests", { prompt: filter });
    return Array.isArray(results) ? results as FeeHarvestsResponse[] : [];
  } catch (error) {
    console.error(`Error getting FeeHarvests collection at path 'feeHarvests': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FeeHarvests collection at feeHarvests
 
  Read Operation Details: Anyone can read harvest history for transparency. Shows all past fee harvests with amounts and timestamps.
  
 */
export function subscribeAllFeeHarvests(callback: (data: FeeHarvestsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("feeHarvests", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FeeHarvestsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FeeHarvests collection at path '${"feeHarvests"}': ${formatError(error)}`);
    }
  });
}

// --- Path: vrfSettlements/$drawingId ---

export interface VrfSettlementsRequest {
  entryId: string;
  winner: AddressType;
  payout: number | TimeOperation | IncrementOperation | TokenAmount;
  fees: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface VrfSettlementsResponse {
  entryId: string;
  winner: string;
  payout: number;
  fees: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a VrfSettlements operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildVrfSettlements(drawingId: string, data?: VrfSettlementsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `vrfSettlements/${drawingId}`, document: doc };
}

/**
 * Admin only. Creates settlement by passing entryId (the winning entry ID in format drawId_wallet), winner wallet address, payout amount (in lamports after fees calculated), and fees amount. Hook validates: (1) drawing exists with result, (2) not already settled, (3) entry exists with matching idx to result, (4) entry wallet matches winner. Then transfers payout to winner, fees to admin, and marks drawing as settled. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setVrfSettlements(drawingId: string, data?: VrfSettlementsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`vrfSettlements/${drawingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting VrfSettlements: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view settlement records for transparency.
   (Get Single Item)
 */
export async function getVrfSettlements(drawingId: string): Promise<VrfSettlementsResponse | null> {
  try {
    const result = await get(`vrfSettlements/${drawingId}`);
    return result as VrfSettlementsResponse | null;
  } catch (error) {
    console.error(`Error getting VrfSettlements: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single VrfSettlements document. (
  Read Operation Details: Anyone can view settlement records for transparency.
  )
 */
export function subscribeVrfSettlements(callback: (data: VrfSettlementsResponse | null) => void, drawingId: string): Promise<() => Promise<void>> {
  return subscribe(`vrfSettlements/${drawingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as VrfSettlementsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to VrfSettlements at path '${`vrfSettlements/${drawingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many VrfSettlements items from collection vrfSettlements
 
  Read Operation Details: Anyone can view settlement records for transparency.
  
 */
export async function getManyVrfSettlements(filter: string = ""): Promise<VrfSettlementsResponse[]> {
  try {
    const results = await get("vrfSettlements", { prompt: filter });
    return Array.isArray(results) ? results as VrfSettlementsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfSettlements collection at path 'vrfSettlements': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfSettlements collection at vrfSettlements
 
  Read Operation Details: Anyone can view settlement records for transparency.
  
 */
export function subscribeManyVrfSettlements(callback: (data: VrfSettlementsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfSettlements", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfSettlementsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfSettlements collection at path '${"vrfSettlements"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all VrfSettlements items from collection vrfSettlements
 
  Read Operation Details: Anyone can view settlement records for transparency.
  
 */
export async function getAllVrfSettlements(filter: string = ""): Promise<VrfSettlementsResponse[]> {
  try {
    const results = await get("vrfSettlements", { prompt: filter });
    return Array.isArray(results) ? results as VrfSettlementsResponse[] : [];
  } catch (error) {
    console.error(`Error getting VrfSettlements collection at path 'vrfSettlements': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in VrfSettlements collection at vrfSettlements
 
  Read Operation Details: Anyone can view settlement records for transparency.
  
 */
export function subscribeAllVrfSettlements(callback: (data: VrfSettlementsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("vrfSettlements", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as VrfSettlementsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to VrfSettlements collection at path '${"vrfSettlements"}': ${formatError(error)}`);
    }
  });
}

// --- Path: transfers/$transferId ---

export interface TransfersRequest {
  from: AddressType;
  to: AddressType;
  amt: number | TimeOperation | IncrementOperation | TokenAmount;
  mint: AddressType;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface TransfersResponse {
  from: string;
  to: string;
  amt: number;
  mint: string;
  ts: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a Transfers operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildTransfers(transferId: string, data?: TransfersRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `transfers/${transferId}`, document: doc };
}

/**
 * Authenticated users can create transfers FROM their own wallet only (from must equal user address). Hook executes @TokenPlugin.transfer onchain to move tokens. Amount is in raw units (9 decimals for PBALL). isPassthrough means data stored offchain only to reduce costs. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setTransfers(transferId: string, data?: TransfersRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`transfers/${transferId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Transfers: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
   (Get Single Item)
 */
export async function getTransfers(transferId: string): Promise<TransfersResponse | null> {
  try {
    const result = await get(`transfers/${transferId}`);
    return result as TransfersResponse | null;
  } catch (error) {
    console.error(`Error getting Transfers: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Transfers document. (
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
  )
 */
export function subscribeTransfers(callback: (data: TransfersResponse | null) => void, transferId: string): Promise<() => Promise<void>> {
  return subscribe(`transfers/${transferId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as TransfersResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Transfers at path '${`transfers/${transferId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Transfers items from collection transfers
 
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
  
 */
export async function getManyTransfers(filter: string = ""): Promise<TransfersResponse[]> {
  try {
    const results = await get("transfers", { prompt: filter });
    return Array.isArray(results) ? results as TransfersResponse[] : [];
  } catch (error) {
    console.error(`Error getting Transfers collection at path 'transfers': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Transfers collection at transfers
 
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
  
 */
export function subscribeManyTransfers(callback: (data: TransfersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("transfers", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TransfersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Transfers collection at path '${"transfers"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Transfers items from collection transfers
 
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
  
 */
export async function getAllTransfers(filter: string = ""): Promise<TransfersResponse[]> {
  try {
    const results = await get("transfers", { prompt: filter });
    return Array.isArray(results) ? results as TransfersResponse[] : [];
  } catch (error) {
    console.error(`Error getting Transfers collection at path 'transfers': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Transfers collection at transfers
 
  Read Operation Details: Anyone can read transfer records for transparency and history viewing.
  
 */
export function subscribeAllTransfers(callback: (data: TransfersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("transfers", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TransfersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Transfers collection at path '${"transfers"}': ${formatError(error)}`);
    }
  });
}

// --- End Generated SDK ---
